<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Fdm.Data.ResourcePlanningTool.Models\Fdm.Data.ResourcePlanningTool.Models.csproj" />
		<ProjectReference Include="..\Fdm.WebAPI\Fdm.WebAPI.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.1" />
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="6.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.10" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NBuilder" Version="6.1.0" />
	</ItemGroup>
</Project>