// <auto-generated />
using System;
using Fdm.Data.ResourcePlanningTool.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fdm.Data.ResourcePlanningTool.Dal.Migrations
{
    [DbContext(typeof(ResourcePlanningToolContext))]
    [Migration("20230424194848_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PathwayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreparationNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Provisional")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VenueId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Virtual")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PathwayId");

                    b.HasIndex("RegionId");

                    b.HasIndex("VenueId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.CourseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExtra")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PathwayTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreparationNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PathwayTemplateId");

                    b.HasIndex("RegionId");

                    b.ToTable("CourseTemplates");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPopUp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Pathway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPond")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathwayCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PathwayTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PathwayCode")
                        .IsUnique();

                    b.HasIndex("PathwayTypeId");

                    b.HasIndex("ProgrammeId");

                    b.HasIndex("RegionId");

                    b.ToTable("Pathways");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.PathwayTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PathwayTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PathwayTypeId");

                    b.HasIndex("RegionId");

                    b.ToTable("PathwayTemplates");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.PathwayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConcludingPathway")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LMSAccessGroup")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Colour")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PathwayTypes");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Programme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCoreTrainer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTutor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OfficeId");

                    b.HasIndex("RegionId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Trainer_Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainerRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("TrainerRoleId");

                    b.ToTable("Trainer_Courses");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.TrainerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrainerRoles");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OfficeId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Country", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Course", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Pathway", "Pathway")
                        .WithMany("Courses")
                        .HasForeignKey("PathwayId");

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Region", null)
                        .WithMany("Courses")
                        .HasForeignKey("RegionId");

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Venue", "Venue")
                        .WithMany("Course")
                        .HasForeignKey("VenueId");

                    b.Navigation("Pathway");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.CourseTemplate", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.PathwayTemplate", "PathwayTemplate")
                        .WithMany("CourseTemplates")
                        .HasForeignKey("PathwayTemplateId");

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Region", null)
                        .WithMany("CourseTemplates")
                        .HasForeignKey("RegionId");

                    b.Navigation("PathwayTemplate");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Holiday", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Office", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Country", "Country")
                        .WithMany("Offices")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Pathway", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.PathwayType", "PathwayType")
                        .WithMany("Pathways")
                        .HasForeignKey("PathwayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Programme", "Programme")
                        .WithMany("Pathways")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Region", "Region")
                        .WithMany("Pathways")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PathwayType");

                    b.Navigation("Programme");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.PathwayTemplate", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.PathwayType", "PathwayType")
                        .WithMany("PathwayTemplates")
                        .HasForeignKey("PathwayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PathwayType");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Trainer", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Office", "Office")
                        .WithMany("Trainers")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Region", null)
                        .WithMany("Trainers")
                        .HasForeignKey("RegionId");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Trainer_Course", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Course", "Course")
                        .WithMany("TrainerCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Trainer", "Trainer")
                        .WithMany("Trainer_Courses")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.TrainerRole", "TrainerRole")
                        .WithMany("Trainer_Courses")
                        .HasForeignKey("TrainerRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainer");

                    b.Navigation("TrainerRole");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Venue", b =>
                {
                    b.HasOne("Fdm.Data.ResourcePlanningTool.Models.Office", "Office")
                        .WithMany("Venues")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Country", b =>
                {
                    b.Navigation("Offices");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Course", b =>
                {
                    b.Navigation("TrainerCourses");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Office", b =>
                {
                    b.Navigation("Trainers");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Pathway", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.PathwayTemplate", b =>
                {
                    b.Navigation("CourseTemplates");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.PathwayType", b =>
                {
                    b.Navigation("PathwayTemplates");

                    b.Navigation("Pathways");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Programme", b =>
                {
                    b.Navigation("Pathways");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Region", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("CourseTemplates");

                    b.Navigation("Courses");

                    b.Navigation("Pathways");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Trainer", b =>
                {
                    b.Navigation("Trainer_Courses");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.TrainerRole", b =>
                {
                    b.Navigation("Trainer_Courses");
                });

            modelBuilder.Entity("Fdm.Data.ResourcePlanningTool.Models.Venue", b =>
                {
                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
